### ISSUE TITLE
Big black border

### ISSUE THREAD

**Issue by kxygk** [flathub/com.github.mdh34.quickdocs#1]
The app launches and works but there is a huge black border/background around the whole application making it unusable. It also have no top toolbar (but Ctrl+Q works, so I can exit..). I'm running Debian-testing + Fluxbox

**Comment by mdh34** [comment]
I noticed the same problem with KDE, I believe it might be the patched theme interfering with things

could you test the attached .flatpak to see if it fixes your issue?
(you can just install it by running `flatpak install no-theme.flatpak`)

[no-theme.flatpak.zip](https://github.com/flathub/com.github.mdh34.quickdocs/files/2067719/no-theme.flatpak.zip)

**Comment by kxygk** [comment]
yep, that works correctly :)

**Comment by mdh34** [comment]
Fixed in master
